[[remove]]
directory = "target\\"

[[check]]
type = "Exclude"
directory = "test\\"
id = "STAN-0208"

[[check]]
type = "Exclude"
file = "src\\Stan\\Cabal.hs"
id = "STAN-0212"

[[check]]
type = "Exclude"
file = "src\\Stan\\Example.hs"
filter = "all"
