#!/usr/bin/env bash

set -euxo pipefail

# This script is for Stan Report testing
# Runs Stan with some predefined config options.

cabal run stan -- check --exclude --filter-all --directory=test/ \
     check --include --filter-all --scope-all \
     check --exclude --id=STAN-0002 --scope-all \
     check --exclude --id=STAN-0001 --file=src/MyFile.hs \
     ignore --id="OBS-00001" \
     report
