resolver: lts-18.18

extra-deps:
- git: https://github.com/mbg/sarif.git
  commit: 08d1a9878de944b8de0a67dc4cf0f0634b23fd08
- colourista-0.1.0.1
- dir-traverse-0.2.2.3
- dlist-0.8.0.8
- extensions-0.0.0.1
- microaeson-0.1.0.0
- optparse-applicative-0.15.1.0
# When changing relude version, also change it in .github/workflows/ci.yml
- relude-1.0.0.1
- slist-0.1.1.0
- trial-0.0.0.0
- trial-optparse-applicative-0.0.0.0
- trial-tomland-0.0.0.0
